"""
Constant lists of entities to be used by DummyData functions.
"""

CITIES = [
    'Plano',
    'St. Paul',
    'Long Beach',
    'Omaha',
    'San Jose',
    'El Paso',
    'Rochester',
    'Portland',
    'Aurora',
    'Buffalo',
    'Virginia Beach',
    'Cleveland',
    'Baton Rouge',
    'Bakersfield',
    'Anchorage',
    'North Hempstead',
    'Lexington-Fayette',
    'Fort Worth',
    'Memphis',
    'Honolulu',
    'Las Vegas',
    'New York',
    'St. Petersburg',
    'Colorado Springs',
    'St. Louis',
    'Chicago',
    'Phoenix',
    'Jersey City',
    'Detroit',
    'Akron',
    'Wichita',
    'Miami',
    'Chandler',
    'Lubbock',
    'Oklahoma City',
    'Kansas City',
    'Stockton',
    'San Diego',
    'Indianapolis',
    'Reno',
    'Huntington',
    'Hialeah',
    'Henderson',
    'Laredo',
    'Durham',
    'Milwaukee',
    'Newark',
    'Minneapolis',
    'Dallas',
    'Chesapeake',
]


STATES = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
]


STREETS = [
    '2nd Street',
    'Clark Street',
    'Circle Drive',
    'Catherine Street',
    'Route 5',
    'Railroad Street',
    'Garden Street',
    'Pin Oak Drive',
    'Olive Street',
    'Cambridge Court',
    'Columbia Street',
    'Queen Street',
    'Fieldstone Drive',
    '1st Street',
    'Garfield Avenue',
    'Adams Avenue',
    'Holly Drive',
    'Forest Street',
    'Grove Street',
    '2nd Street East',
    'Wood Street',
    'North Avenue',
    'West Avenue',
    'Hawthorne Lane',
    'Evergreen Lane',
    'Central Avenue',
    'Maple Street',
    'Route 64',
    '1st Avenue',
    'Maiden Lane',
    'Cedar Lane',
    'Poplar Street',
    'Beech Street',
    'Tanglewood Drive',
    'Bay Street',
    'Route 2',
    'Sherwood Drive',
    'Marshall Street',
    'Walnut Street',
    'Lawrence Street',
    'Lexington Drive',
    'Oak Lane',
    'Atlantic Avenue',
    'Willow Drive',
    'Grant Street',
    'Route 100',
    'Union Street',
    'Summer Street',
    '4th Street South',
    '3rd Street North',
]


COUNTRIES = [
    'Vatican City',
    'Antigua and Barbuda',
    'Guatemala',
    'Cyprus',
    'Albania',
    'Somalia',
    'Ecuador',
    'Kenya',
    'Estonia',
    'Mozambique',
    'Czech Republic',
    'Lebanon',
    'Libya',
    'El Salvador',
    'South Africa',
    'Norway',
    'Bhutan',
    'Liberia',
    'Macedonia',
    'Brazil',
    'Venezuela',
    'Qatar',
    'Oman',
    'Kuwait',
    'Fiji',
    'Nauru',
    'Paraguay',
    'Kyrgyzstan',
    'Angola',
    'Malawi',
    'Gambia',
    'Mauritania',
    'Jordan',
    'Kosovo',
    'Indonesia',
    'Monaco',
    'Australia',
    'Cameroon',
    'Sudan',
    'Tanzania',
    'Uruguay',
    'Palau',
    'Senegal',
    'Mauritius',
    'England',
    'Slovenia',
    'Afghanistan',
    'Madagascar',
    'Serbia',
    'Tunisia',
]


COMPANIES = [
    'Physcone',
    'Finjocane',
    'J-find',
    'Treefix',
    'Keyphase',
    'Funtinin',
    'Aptrax',
    'Donfase',
    'Bamcon',
    'Tantech',
    'Tonruntone',
    'Zenhigh',
    'Waredex',
    'Mediaplanet',
    'Keyelectrics',
    'biostreet',
    'Villalane',
    'Unala',
    'Truetam',
    'Y-dom',
    'Good-zoom',
    'Vivaholding',
    'Gravejob',
    'Funholding',
    'Movetam',
    'Zoozooplus',
    'Zaamtechno',
    'zonice',
    'Soloity',
    'beta-taxon',
    'Quadtech',
    'Zimhattech',
    'Ranktrans',
    'Soloelectrics',
    'Doublelab',
    'Biotechi',
    'Golden-lane',
    'ranlax',
    'Grooveholding',
    'Y-com',
    'Silvercode',
    'Howranfase',
    'Zooelectrics',
    'Freetone',
    'Opencare',
    'Kintech',
    'Ventostreet',
    'Tanlax',
    'Xxx-plus',
    'Fasela',
]


FIRST_NAMES = [
    'Laci',
    'Anabel',
    'Casandra',
    'Celestina',
    'Felicitas',
    'Sandee',
    'Vincent',
    'Minnie',
    'Bessie',
    'Cordell',
    'Valda',
    'Ona',
    'Alex',
    'Rene',
    'Sheri',
    'Franchesca',
    'Max',
    'Earnestine',
    'Nadia',
    'Hilde',
    'Jennie',
    'Gayla',
    'Harriet',
    'Yuko',
    'Jaleesa',
    'Judie',
    'Shaunda',
    'Rowena',
    'Earline',
    'Deidre',
    'Claudio',
    'Emmitt',
    'Georgetta',
    'Rosalina',
    'Berniece',
    'Brittaney',
    'Mindi',
    'Elizbeth',
    'Dulcie',
    'Theo',
    'Shella',
    'Jerold',
    'Denice',
    'Rebeca',
    'Concetta',
    'Lottie',
    'Esther',
    'Marcela',
    'Rick',
    'Marylouise',
]


LAST_NAMES = [
    'Landenna',
    'Dongoski',
    'Margaitis',
    'Daboni',
    'Wegman',
    'Bickmore',
    'Lomeli',
    'Prichard',
    'Isome',
    'Sheahan',
    'Neilson',
    'Wacquant',
    'Bhide',
    'St martin',
    'Reid-cunningham',
    'Pesarin',
    'Sewall',
    'Litwin',
    'Cichon',
    'Glover',
    'Kinnaman',
    'Imamoglu',
    'Hurd',
    'Fredexric',
    'Rhoades',
    'Chiogna',
    'Perali',
    'Afzal-khan',
    'Pieraccini',
    'Seheult',
    'Corgain',
    'Pindar',
    'Montesquieu',
    'Casteris',
    'Schickele',
    'Gabor',
    'Bator',
    'Mango',
    'Lubin',
    'Franci',
    'Lipshutz',
    'Carder',
    'Torff',
    'Korsgaard',
    'Schleifer',
    'Vetrovs',
    'Levin',
    'Philips',
    'Stanton',
    'Vittadini',
]
